
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://Service.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param code
     * @param montant
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterMontant", targetNamespace = "http://Service.example.org/", className = "service.AjouterMontant")
    @ResponseWrapper(localName = "ajouterMontantResponse", targetNamespace = "http://Service.example.org/", className = "service.AjouterMontantResponse")
    @Action(input = "http://Service.example.org/BanqueService/ajouterMontantRequest", output = "http://Service.example.org/BanqueService/ajouterMontantResponse")
    public void ajouterMontant(
        @WebParam(name = "code", targetNamespace = "")
        Long code,
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param dateCreation
     * @param code
     * @param mdp
     * @param solde
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://Service.example.org/", className = "service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://Service.example.org/", className = "service.AddResponse")
    @Action(input = "http://Service.example.org/BanqueService/addRequest", output = "http://Service.example.org/BanqueService/addResponse")
    public void add(
        @WebParam(name = "code", targetNamespace = "")
        Long code,
        @WebParam(name = "dateCreation", targetNamespace = "")
        String dateCreation,
        @WebParam(name = "solde", targetNamespace = "")
        Double solde,
        @WebParam(name = "MDP", targetNamespace = "")
        String mdp);

    /**
     * 
     * @param code
     */
    @WebMethod
    @RequestWrapper(localName = "retirerCompte", targetNamespace = "http://Service.example.org/", className = "service.RetirerCompte")
    @ResponseWrapper(localName = "retirerCompteResponse", targetNamespace = "http://Service.example.org/", className = "service.RetirerCompteResponse")
    @Action(input = "http://Service.example.org/BanqueService/retirerCompteRequest", output = "http://Service.example.org/BanqueService/retirerCompteResponse")
    public void retirerCompte(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

    /**
     * 
     * @param code
     * @param montant
     */
    @WebMethod
    @RequestWrapper(localName = "retirerMontant", targetNamespace = "http://Service.example.org/", className = "service.RetirerMontant")
    @ResponseWrapper(localName = "retirerMontantResponse", targetNamespace = "http://Service.example.org/", className = "service.RetirerMontantResponse")
    @Action(input = "http://Service.example.org/BanqueService/retirerMontantRequest", output = "http://Service.example.org/BanqueService/retirerMontantResponse")
    public void retirerMontant(
        @WebParam(name = "code", targetNamespace = "")
        Long code,
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertir", targetNamespace = "http://Service.example.org/", className = "service.Convertir")
    @ResponseWrapper(localName = "convertirResponse", targetNamespace = "http://Service.example.org/", className = "service.ConvertirResponse")
    @Action(input = "http://Service.example.org/BanqueService/convertirRequest", output = "http://Service.example.org/BanqueService/convertirResponse")
    public double convertir(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "afficherlisteComptes", targetNamespace = "http://Service.example.org/", className = "service.AfficherlisteComptes")
    @ResponseWrapper(localName = "afficherlisteComptesResponse", targetNamespace = "http://Service.example.org/", className = "service.AfficherlisteComptesResponse")
    @Action(input = "http://Service.example.org/BanqueService/afficherlisteComptesRequest", output = "http://Service.example.org/BanqueService/afficherlisteComptesResponse")
    public String afficherlisteComptes();

}
